"""initial schema

Revision ID: e143918e6d1a
Revises: 
Create Date: 2026-08-20 14:16:57.568391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e143918e6d1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archdioceses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('canonical_erection_date', sa.Date(), nullable=True),
    sa.Column('patron_saint', sa.String(length=100), nullable=True),
    sa.Column('see_city', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archdioceses_id'), 'archdioceses', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('document_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_rw', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=True)
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_index(op.f('ix_document_types_is_deleted'), 'document_types', ['is_deleted'], unique=False)
    op.create_table('land_use_categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_rw', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_use_categories_code'), 'land_use_categories', ['code'], unique=True)
    op.create_index(op.f('ix_land_use_categories_id'), 'land_use_categories', ['id'], unique=False)
    op.create_index(op.f('ix_land_use_categories_is_deleted'), 'land_use_categories', ['is_deleted'], unique=False)
    op.create_table('surveys',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('survey_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('archdiocese_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_index(op.f('ix_surveys_is_deleted'), 'surveys', ['is_deleted'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ARCHBISHOP', 'VICAR_GENERAL', 'CHANCELLOR', 'ECONOMO', 'DEAN', 'PARISH_PRIEST', 'PARISH_VICAR', 'PARISH_SECRETARY', 'MINISTRY_LEADER', 'READ_ONLY_AUDITOR', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deanery_id'), 'users', ['deanery_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_parish_id'), 'users', ['parish_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('deaneries',
    sa.Column('archdiocese_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('vicar_forane_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archdiocese_id'], ['archdioceses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_deaneries_id'), 'deaneries', ['id'], unique=False)
    op.create_index(op.f('ix_deaneries_is_deleted'), 'deaneries', ['is_deleted'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('archdiocese_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('commission_id', sa.UUID(), nullable=True),
    sa.Column('council_id', sa.UUID(), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('priest_id', sa.UUID(), nullable=True),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.create_table('survey_responses',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('respondent_name', sa.String(length=200), nullable=True),
    sa.Column('respondent_parish_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    op.create_index(op.f('ix_survey_responses_is_deleted'), 'survey_responses', ['is_deleted'], unique=False)
    op.create_table('parishes',
    sa.Column('deanery_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('patron_saint', sa.String(length=150), nullable=True),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deanery_id'], ['deaneries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parishes_code'), 'parishes', ['code'], unique=True)
    op.create_index(op.f('ix_parishes_id'), 'parishes', ['id'], unique=False)
    op.create_index(op.f('ix_parishes_is_deleted'), 'parishes', ['is_deleted'], unique=False)
    op.create_table('annual_parish_statistics',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('total_catholic_population', sa.Integer(), nullable=False),
    sa.Column('total_catechumens', sa.Integer(), nullable=False),
    sa.Column('total_families', sa.Integer(), nullable=False),
    sa.Column('infant_baptisms', sa.Integer(), nullable=False),
    sa.Column('adult_baptisms', sa.Integer(), nullable=False),
    sa.Column('first_communions', sa.Integer(), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('marriages_both_catholic', sa.Integer(), nullable=False),
    sa.Column('marriages_mixed_religion', sa.Integer(), nullable=False),
    sa.Column('christian_funerals', sa.Integer(), nullable=False),
    sa.Column('catholic_schools_count', sa.Integer(), nullable=False),
    sa.Column('students_count', sa.Integer(), nullable=False),
    sa.Column('health_centers_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_parish_statistics_id'), 'annual_parish_statistics', ['id'], unique=False)
    op.create_table('archive_ledger_books',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('sacrament_type', sa.Enum('BAPTISM', 'FIRST_COMMUNION', 'CONFIRMATION', 'MATRIMONY', 'HOLY_ORDERS', 'RELIGIOUS_PROFESSION', 'ANOINTING_OF_THE_SICK', 'CHRISTIAN_FUNERAL', name='sacrament_type_archive_enum'), nullable=False),
    sa.Column('book_title', sa.String(length=200), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.String(length=20), nullable=False),
    sa.Column('shelf_location', sa.String(length=100), nullable=True),
    sa.Column('total_scanned_pages', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_ledger_books_id'), 'archive_ledger_books', ['id'], unique=False)
    op.create_index(op.f('ix_archive_ledger_books_is_deleted'), 'archive_ledger_books', ['is_deleted'], unique=False)
    op.create_table('centrales',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('patron_saint', sa.String(length=150), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centrales_id'), 'centrales', ['id'], unique=False)
    op.create_index(op.f('ix_centrales_is_deleted'), 'centrales', ['is_deleted'], unique=False)
    op.create_table('commissions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('FAMILY', 'EDUCATION', 'YOUTH', 'LITURGY', 'CARITAS_SOCIAL', 'VOCATIONS', 'COMMUNICATIONS', 'JUSTICE_PEACE', 'HEALTH', 'OTHER', name='commission_category_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('patron_saint', sa.String(length=100), nullable=True),
    sa.Column('archdiocese_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('leader_name', sa.String(length=200), nullable=True),
    sa.Column('leader_phone', sa.String(length=50), nullable=True),
    sa.Column('meeting_schedule', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_id'), 'commissions', ['id'], unique=False)
    op.create_index(op.f('ix_commissions_is_deleted'), 'commissions', ['is_deleted'], unique=False)
    op.create_table('councils',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('council_type', sa.Enum('DIOCESAN_PASTORAL', 'PRESBYTERIUM', 'COLLEGE_OF_CONSULTERS', 'ECONOMIC_AFFAIRS', 'PARISH_PASTORAL', 'PARISH_ECONOMIC', name='council_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archdiocese_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('president_name', sa.String(length=200), nullable=True),
    sa.Column('convener_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_councils_id'), 'councils', ['id'], unique=False)
    op.create_index(op.f('ix_councils_is_deleted'), 'councils', ['is_deleted'], unique=False)
    op.create_table('events',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.Enum('LITURGICAL', 'PASTORAL', 'ADMINISTRATIVE', 'SOCIAL', 'TRAINING', name='event_type_enum'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('archdiocese_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_table('land_parcels',
    sa.Column('upi', sa.String(length=50), nullable=False),
    sa.Column('title_deed_number', sa.String(length=100), nullable=True),
    sa.Column('parcel_name', sa.String(length=200), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('land_use', sa.Enum('CHURCH_COMPOUND', 'CENTRALE_CHAPEL', 'HEALTH_FACILITY', 'EDUCATIONAL', 'AGRICULTURAL', 'COMMERCIAL_RENTAL', 'CONVENT_MONASTERY', 'CEMETERY', 'VACANT_RESERVE', name='land_use_enum'), nullable=False),
    sa.Column('tenure_status', sa.Enum('FREEHOLD', 'EMPHYTEUTIC_LEASE', 'DISPUTED', 'IN_REGISTRATION', name='tenure_status_enum'), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('estimated_value_rwf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('cell', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deanery_id'], ['deaneries.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_parcels_id'), 'land_parcels', ['id'], unique=False)
    op.create_index(op.f('ix_land_parcels_is_deleted'), 'land_parcels', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_land_parcels_upi'), 'land_parcels', ['upi'], unique=True)
    op.create_table('ministries',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('COMMISSION', 'CHOIR', 'ECCLESIAL_MOVEMENT', 'COUNCIL', 'YOUTH_GUILD', name='ministry_category_enum'), nullable=False),
    sa.Column('patron_saint', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leader_name', sa.String(length=200), nullable=True),
    sa.Column('leader_phone', sa.String(length=50), nullable=True),
    sa.Column('meeting_schedule', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ministries_id'), 'ministries', ['id'], unique=False)
    op.create_index(op.f('ix_ministries_is_deleted'), 'ministries', ['is_deleted'], unique=False)
    op.create_table('physical_locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('building', sa.String(length=200), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('shelf', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_locations_id'), 'physical_locations', ['id'], unique=False)
    op.create_index(op.f('ix_physical_locations_is_deleted'), 'physical_locations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_physical_locations_location_code'), 'physical_locations', ['location_code'], unique=True)
    op.create_table('priests',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('clergy_type', sa.Enum('BISHOP', 'DIOCESAN_PRIEST', 'RELIGIOUS_PRIEST', 'PERMANENT_DEACON', 'TRANSITIONAL_DEACON', 'RELIGIOUS_BROTHER', 'RELIGIOUS_SISTER', 'SEMINARIAN', name='clergy_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE_DUTY', 'RETIRED', 'STUDIES', 'ON_LEAVE', 'MISSION_OUTSIDE', 'DECEASED', name='clergy_status_enum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ordination_date', sa.Date(), nullable=True),
    sa.Column('ordaining_bishop', sa.String(length=200), nullable=True),
    sa.Column('congregation', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('current_parish_id', sa.UUID(), nullable=True),
    sa.Column('current_role', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priests_id'), 'priests', ['id'], unique=False)
    op.create_index(op.f('ix_priests_is_deleted'), 'priests', ['is_deleted'], unique=False)
    op.create_table('appointments',
    sa.Column('person_first_name', sa.String(length=100), nullable=False),
    sa.Column('person_last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Enum('ARCHBISHOP', 'AUXILIARY_BISHOP', 'VICAR_GENERAL', 'EPISCOPAL_VICAR', 'CHANCELLOR', 'VICE_CHANCELLOR', 'ECONOMO', 'DEAN', 'PARISH_PRIEST', 'PARISH_VICAR', 'PARISH_SECRETARY', name='appointment_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'SUSPENDED', name='appointment_status_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('decree_reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('archdiocese_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('priest_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['priest_id'], ['priests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_is_deleted'), 'appointments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_table('archive_scanned_pages',
    sa.Column('ledger_book_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_file_path', sa.String(length=500), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_book_id'], ['archive_ledger_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_scanned_pages_id'), 'archive_scanned_pages', ['id'], unique=False)
    op.create_table('building_assets',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('building_type', sa.String(length=100), nullable=False),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('floors_count', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_assets_id'), 'building_assets', ['id'], unique=False)
    op.create_index(op.f('ix_building_assets_is_deleted'), 'building_assets', ['is_deleted'], unique=False)
    op.create_table('clergy_assignments',
    sa.Column('priest_id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('role_title', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('decree_reference_number', sa.String(length=100), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['priests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clergy_assignments_id'), 'clergy_assignments', ['id'], unique=False)
    op.create_table('land_documents',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_documents_id'), 'land_documents', ['id'], unique=False)
    op.create_table('lease_agreements',
    sa.Column('lease_number', sa.String(length=50), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('lessee_name', sa.String(length=200), nullable=False),
    sa.Column('lessee_contact', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('monthly_rent_rwf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('contract_document_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_agreements_id'), 'lease_agreements', ['id'], unique=False)
    op.create_index(op.f('ix_lease_agreements_is_deleted'), 'lease_agreements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lease_agreements_lease_number'), 'lease_agreements', ['lease_number'], unique=True)
    op.create_table('mass_schedules',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('centrale_id', sa.UUID(), nullable=True),
    sa.Column('mass_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('celebrant_name', sa.String(length=200), nullable=True),
    sa.Column('liturgical_feast', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['centrale_id'], ['centrales.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mass_schedules_id'), 'mass_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_mass_schedules_is_deleted'), 'mass_schedules', ['is_deleted'], unique=False)
    op.create_table('meetings',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('council_id', sa.UUID(), nullable=True),
    sa.Column('commission_id', sa.UUID(), nullable=True),
    sa.Column('archdiocese_id', sa.UUID(), nullable=True),
    sa.Column('deanery_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_is_deleted'), 'meetings', ['is_deleted'], unique=False)
    op.create_table('parcel_ownership_history',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('ownership_start_date', sa.Date(), nullable=False),
    sa.Column('ownership_end_date', sa.Date(), nullable=True),
    sa.Column('transfer_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_ownership_history_id'), 'parcel_ownership_history', ['id'], unique=False)
    op.create_index(op.f('ix_parcel_ownership_history_is_deleted'), 'parcel_ownership_history', ['is_deleted'], unique=False)
    op.create_table('qr_code_registry',
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Enum('CERTIFICATE', 'DOCUMENT', 'LAND_PARCEL', name='qr_code_purpose_enum'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('certificate_issue_id', sa.UUID(), nullable=True),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_code_registry_id'), 'qr_code_registry', ['id'], unique=False)
    op.create_index(op.f('ix_qr_code_registry_is_deleted'), 'qr_code_registry', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_qr_code_registry_token'), 'qr_code_registry', ['token'], unique=True)
    op.create_table('small_christian_communities',
    sa.Column('centrale_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('patron_saint', sa.String(length=150), nullable=True),
    sa.Column('leader_name', sa.String(length=200), nullable=True),
    sa.Column('leader_phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['centrale_id'], ['centrales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_small_christian_communities_id'), 'small_christian_communities', ['id'], unique=False)
    op.create_index(op.f('ix_small_christian_communities_is_deleted'), 'small_christian_communities', ['is_deleted'], unique=False)
    op.create_table('storage_cabinets',
    sa.Column('cabinet_number', sa.String(length=50), nullable=False),
    sa.Column('drawer_count', sa.Integer(), nullable=False),
    sa.Column('current_capacity_pct', sa.Integer(), nullable=False),
    sa.Column('physical_location_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['physical_location_id'], ['physical_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_cabinets_id'), 'storage_cabinets', ['id'], unique=False)
    op.create_index(op.f('ix_storage_cabinets_is_deleted'), 'storage_cabinets', ['is_deleted'], unique=False)
    op.create_table('tax_records',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('assessed_value_rwf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount_rwf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_records_id'), 'tax_records', ['id'], unique=False)
    op.create_index(op.f('ix_tax_records_is_deleted'), 'tax_records', ['is_deleted'], unique=False)
    op.create_table('families',
    sa.Column('family_code', sa.String(length=50), nullable=False),
    sa.Column('family_name', sa.String(length=200), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('centrale_id', sa.UUID(), nullable=True),
    sa.Column('scc_id', sa.UUID(), nullable=True),
    sa.Column('residence_address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['centrale_id'], ['centrales.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['scc_id'], ['small_christian_communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_family_code'), 'families', ['family_code'], unique=True)
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_is_deleted'), 'families', ['is_deleted'], unique=False)
    op.create_table('lease_payment_schedule',
    sa.Column('lease_agreement_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_rwf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lease_agreement_id'], ['lease_agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_payment_schedule_id'), 'lease_payment_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_lease_payment_schedule_is_deleted'), 'lease_payment_schedule', ['is_deleted'], unique=False)
    op.create_table('mass_intentions',
    sa.Column('mass_schedule_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_name', sa.String(length=200), nullable=False),
    sa.Column('requested_by_phone', sa.String(length=50), nullable=True),
    sa.Column('intention_type', sa.Enum('REQUIEM', 'THANKSGIVING', 'SPECIAL_PETITION', name='intention_type_enum'), nullable=False),
    sa.Column('intention_text', sa.Text(), nullable=False),
    sa.Column('stipend_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mass_schedule_id'], ['mass_schedules.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mass_intentions_id'), 'mass_intentions', ['id'], unique=False)
    op.create_index(op.f('ix_mass_intentions_is_deleted'), 'mass_intentions', ['is_deleted'], unique=False)
    op.create_table('meeting_minutes',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_minutes_id'), 'meeting_minutes', ['id'], unique=False)
    op.create_table('tax_payments',
    sa.Column('tax_record_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid_rwf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tax_record_id'], ['tax_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_payments_id'), 'tax_payments', ['id'], unique=False)
    op.create_index(op.f('ix_tax_payments_is_deleted'), 'tax_payments', ['is_deleted'], unique=False)
    op.create_table('faithful',
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('christian_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender_enum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=150), nullable=True),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=200), nullable=True),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('canonical_status', sa.Enum('CATECHUMEN', 'BAPTIZED', 'CONFIRMED', 'CANONICAL_MARRIAGE', 'CIVIL_ONLY', 'CLERGY_OR_RELIGIOUS', 'DECEASED', name='canonical_status_enum'), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('family_role', sa.Enum('HEAD', 'SPOUSE', 'CHILD', 'DEPENDENT', 'OTHER', name='family_role_enum'), nullable=False),
    sa.Column('scc_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['scc_id'], ['small_christian_communities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id')
    )
    op.create_index(op.f('ix_faithful_id'), 'faithful', ['id'], unique=False)
    op.create_index(op.f('ix_faithful_is_deleted'), 'faithful', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_faithful_registration_number'), 'faithful', ['registration_number'], unique=True)
    op.create_table('anointing_of_the_sick_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('faithful_id', sa.UUID(), nullable=False),
    sa.Column('anointing_date', sa.Date(), nullable=False),
    sa.Column('minister_name', sa.String(length=200), nullable=False),
    sa.Column('place_of_anointing', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anointing_of_the_sick_records_id'), 'anointing_of_the_sick_records', ['id'], unique=False)
    op.create_index(op.f('ix_anointing_of_the_sick_records_is_deleted'), 'anointing_of_the_sick_records', ['is_deleted'], unique=False)
    op.create_table('baptism_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('faithful_id', sa.UUID(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.String(length=20), nullable=False),
    sa.Column('page_number', sa.String(length=20), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False),
    sa.Column('celebration_date', sa.Date(), nullable=False),
    sa.Column('minister_name', sa.String(length=200), nullable=False),
    sa.Column('godfather_name', sa.String(length=200), nullable=True),
    sa.Column('godmother_name', sa.String(length=200), nullable=True),
    sa.Column('marginal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baptism_records_id'), 'baptism_records', ['id'], unique=False)
    op.create_index(op.f('ix_baptism_records_is_deleted'), 'baptism_records', ['is_deleted'], unique=False)
    op.create_table('certificate_issues',
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('sacrament_type', sa.Enum('BAPTISM', 'FIRST_COMMUNION', 'CONFIRMATION', 'MATRIMONY', 'HOLY_ORDERS', 'RELIGIOUS_PROFESSION', 'ANOINTING_OF_THE_SICK', 'CHRISTIAN_FUNERAL', name='sacrament_type_enum'), nullable=False),
    sa.Column('faithful_id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=False),
    sa.Column('qr_code_payload', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index(op.f('ix_certificate_issues_certificate_number'), 'certificate_issues', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_certificate_issues_id'), 'certificate_issues', ['id'], unique=False)
    op.create_table('christian_funeral_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('deceased_faithful_id', sa.UUID(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=False),
    sa.Column('funeral_date', sa.Date(), nullable=False),
    sa.Column('burial_site', sa.String(length=200), nullable=True),
    sa.Column('officiating_priest', sa.String(length=200), nullable=False),
    sa.Column('last_sacraments_received', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deceased_faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_christian_funeral_records_id'), 'christian_funeral_records', ['id'], unique=False)
    op.create_index(op.f('ix_christian_funeral_records_is_deleted'), 'christian_funeral_records', ['is_deleted'], unique=False)
    op.create_table('confirmation_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('faithful_id', sa.UUID(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.String(length=20), nullable=False),
    sa.Column('page_number', sa.String(length=20), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False),
    sa.Column('celebration_date', sa.Date(), nullable=False),
    sa.Column('administering_bishop_or_vicar', sa.String(length=200), nullable=False),
    sa.Column('sponsor_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmation_records_id'), 'confirmation_records', ['id'], unique=False)
    op.create_index(op.f('ix_confirmation_records_is_deleted'), 'confirmation_records', ['is_deleted'], unique=False)
    op.create_table('donations',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('faithful_id', sa.UUID(), nullable=True),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('donation_type', sa.Enum('TITHE', 'OFFERTORY', 'CONSTRUCTION_FUND', 'CARITAS_POOR', 'SPECIAL_COLLECTION', 'MASS_STIPEND', name='donation_type_enum'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MOMO', 'BANK_TRANSFER', 'CHECK', name='payment_method_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('donation_date', sa.Date(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('donor_name_override', sa.String(length=200), nullable=True),
    sa.Column('reference_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_is_deleted'), 'donations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_donations_receipt_number'), 'donations', ['receipt_number'], unique=True)
    op.create_table('first_communion_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('faithful_id', sa.UUID(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.String(length=20), nullable=False),
    sa.Column('page_number', sa.String(length=20), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False),
    sa.Column('celebration_date', sa.Date(), nullable=False),
    sa.Column('celebrant_name', sa.String(length=200), nullable=False),
    sa.Column('catechetical_program_name', sa.String(length=200), nullable=True),
    sa.Column('sponsor_name', sa.String(length=200), nullable=True),
    sa.Column('marginal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_communion_records_id'), 'first_communion_records', ['id'], unique=False)
    op.create_index(op.f('ix_first_communion_records_is_deleted'), 'first_communion_records', ['is_deleted'], unique=False)
    op.create_table('holy_orders_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('ordained_faithful_id', sa.UUID(), nullable=False),
    sa.Column('register_book', sa.String(length=20), nullable=False),
    sa.Column('page_number', sa.String(length=20), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False),
    sa.Column('ordination_date', sa.Date(), nullable=False),
    sa.Column('order_type', sa.Enum('DIACONATE', 'PRIESTHOOD', 'EPISCOPATE', name='holy_orders_order_type_enum'), nullable=False),
    sa.Column('ordaining_prelate', sa.String(length=200), nullable=False),
    sa.Column('diocese_of_incardination', sa.String(length=200), nullable=True),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('marginal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ordained_faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holy_orders_records_id'), 'holy_orders_records', ['id'], unique=False)
    op.create_index(op.f('ix_holy_orders_records_is_deleted'), 'holy_orders_records', ['is_deleted'], unique=False)
    op.create_table('matrimony_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('groom_faithful_id', sa.UUID(), nullable=False),
    sa.Column('bride_faithful_id', sa.UUID(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.String(length=20), nullable=False),
    sa.Column('page_number', sa.String(length=20), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False),
    sa.Column('celebration_date', sa.Date(), nullable=False),
    sa.Column('priest_celebrant', sa.String(length=200), nullable=False),
    sa.Column('witness_1_name', sa.String(length=200), nullable=False),
    sa.Column('witness_2_name', sa.String(length=200), nullable=False),
    sa.Column('dispensations_or_canonical_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bride_faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['groom_faithful_id'], ['faithful.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrimony_records_id'), 'matrimony_records', ['id'], unique=False)
    op.create_index(op.f('ix_matrimony_records_is_deleted'), 'matrimony_records', ['is_deleted'], unique=False)
    op.create_table('religious_profession_records',
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('professed_faithful_id', sa.UUID(), nullable=False),
    sa.Column('register_book', sa.String(length=20), nullable=False),
    sa.Column('page_number', sa.String(length=20), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False),
    sa.Column('profession_date', sa.Date(), nullable=False),
    sa.Column('profession_type', sa.Enum('TEMPORARY_VOWS', 'PERPETUAL_VOWS', name='religious_profession_type_enum'), nullable=False),
    sa.Column('congregation_or_institute', sa.String(length=200), nullable=False),
    sa.Column('superior_name', sa.String(length=200), nullable=True),
    sa.Column('marginal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['professed_faithful_id'], ['faithful.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_religious_profession_records_id'), 'religious_profession_records', ['id'], unique=False)
    op.create_index(op.f('ix_religious_profession_records_is_deleted'), 'religious_profession_records', ['is_deleted'], unique=False)
    # NOTE: ``spatial_ref_sys`` is owned/managed by the PostGIS extension, which is
    # created on the container/image side. We must NOT drop or recreate it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_religious_profession_records_is_deleted'), table_name='religious_profession_records')
    op.drop_index(op.f('ix_religious_profession_records_id'), table_name='religious_profession_records')
    op.drop_table('religious_profession_records')
    op.drop_index(op.f('ix_matrimony_records_is_deleted'), table_name='matrimony_records')
    op.drop_index(op.f('ix_matrimony_records_id'), table_name='matrimony_records')
    op.drop_table('matrimony_records')
    op.drop_index(op.f('ix_holy_orders_records_is_deleted'), table_name='holy_orders_records')
    op.drop_index(op.f('ix_holy_orders_records_id'), table_name='holy_orders_records')
    op.drop_table('holy_orders_records')
    op.drop_index(op.f('ix_first_communion_records_is_deleted'), table_name='first_communion_records')
    op.drop_index(op.f('ix_first_communion_records_id'), table_name='first_communion_records')
    op.drop_table('first_communion_records')
    op.drop_index(op.f('ix_donations_receipt_number'), table_name='donations')
    op.drop_index(op.f('ix_donations_is_deleted'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_confirmation_records_is_deleted'), table_name='confirmation_records')
    op.drop_index(op.f('ix_confirmation_records_id'), table_name='confirmation_records')
    op.drop_table('confirmation_records')
    op.drop_index(op.f('ix_christian_funeral_records_is_deleted'), table_name='christian_funeral_records')
    op.drop_index(op.f('ix_christian_funeral_records_id'), table_name='christian_funeral_records')
    op.drop_table('christian_funeral_records')
    op.drop_index(op.f('ix_certificate_issues_id'), table_name='certificate_issues')
    op.drop_index(op.f('ix_certificate_issues_certificate_number'), table_name='certificate_issues')
    op.drop_table('certificate_issues')
    op.drop_index(op.f('ix_baptism_records_is_deleted'), table_name='baptism_records')
    op.drop_index(op.f('ix_baptism_records_id'), table_name='baptism_records')
    op.drop_table('baptism_records')
    op.drop_index(op.f('ix_anointing_of_the_sick_records_is_deleted'), table_name='anointing_of_the_sick_records')
    op.drop_index(op.f('ix_anointing_of_the_sick_records_id'), table_name='anointing_of_the_sick_records')
    op.drop_table('anointing_of_the_sick_records')
    op.drop_index(op.f('ix_faithful_registration_number'), table_name='faithful')
    op.drop_index(op.f('ix_faithful_is_deleted'), table_name='faithful')
    op.drop_index(op.f('ix_faithful_id'), table_name='faithful')
    op.drop_table('faithful')
    op.drop_index(op.f('ix_tax_payments_is_deleted'), table_name='tax_payments')
    op.drop_index(op.f('ix_tax_payments_id'), table_name='tax_payments')
    op.drop_table('tax_payments')
    op.drop_index(op.f('ix_meeting_minutes_id'), table_name='meeting_minutes')
    op.drop_table('meeting_minutes')
    op.drop_index(op.f('ix_mass_intentions_is_deleted'), table_name='mass_intentions')
    op.drop_index(op.f('ix_mass_intentions_id'), table_name='mass_intentions')
    op.drop_table('mass_intentions')
    op.drop_index(op.f('ix_lease_payment_schedule_is_deleted'), table_name='lease_payment_schedule')
    op.drop_index(op.f('ix_lease_payment_schedule_id'), table_name='lease_payment_schedule')
    op.drop_table('lease_payment_schedule')
    op.drop_index(op.f('ix_families_is_deleted'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_index(op.f('ix_families_family_code'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_tax_records_is_deleted'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_id'), table_name='tax_records')
    op.drop_table('tax_records')
    op.drop_index(op.f('ix_storage_cabinets_is_deleted'), table_name='storage_cabinets')
    op.drop_index(op.f('ix_storage_cabinets_id'), table_name='storage_cabinets')
    op.drop_table('storage_cabinets')
    op.drop_index(op.f('ix_small_christian_communities_is_deleted'), table_name='small_christian_communities')
    op.drop_index(op.f('ix_small_christian_communities_id'), table_name='small_christian_communities')
    op.drop_table('small_christian_communities')
    op.drop_index(op.f('ix_qr_code_registry_token'), table_name='qr_code_registry')
    op.drop_index(op.f('ix_qr_code_registry_is_deleted'), table_name='qr_code_registry')
    op.drop_index(op.f('ix_qr_code_registry_id'), table_name='qr_code_registry')
    op.drop_table('qr_code_registry')
    op.drop_index(op.f('ix_parcel_ownership_history_is_deleted'), table_name='parcel_ownership_history')
    op.drop_index(op.f('ix_parcel_ownership_history_id'), table_name='parcel_ownership_history')
    op.drop_table('parcel_ownership_history')
    op.drop_index(op.f('ix_meetings_is_deleted'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_mass_schedules_is_deleted'), table_name='mass_schedules')
    op.drop_index(op.f('ix_mass_schedules_id'), table_name='mass_schedules')
    op.drop_table('mass_schedules')
    op.drop_index(op.f('ix_lease_agreements_lease_number'), table_name='lease_agreements')
    op.drop_index(op.f('ix_lease_agreements_is_deleted'), table_name='lease_agreements')
    op.drop_index(op.f('ix_lease_agreements_id'), table_name='lease_agreements')
    op.drop_table('lease_agreements')
    op.drop_index(op.f('ix_land_documents_id'), table_name='land_documents')
    op.drop_table('land_documents')
    op.drop_index(op.f('ix_clergy_assignments_id'), table_name='clergy_assignments')
    op.drop_table('clergy_assignments')
    op.drop_index(op.f('ix_building_assets_is_deleted'), table_name='building_assets')
    op.drop_index(op.f('ix_building_assets_id'), table_name='building_assets')
    op.drop_table('building_assets')
    op.drop_index(op.f('ix_archive_scanned_pages_id'), table_name='archive_scanned_pages')
    op.drop_table('archive_scanned_pages')
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_is_deleted'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_priests_is_deleted'), table_name='priests')
    op.drop_index(op.f('ix_priests_id'), table_name='priests')
    op.drop_table('priests')
    op.drop_index(op.f('ix_physical_locations_location_code'), table_name='physical_locations')
    op.drop_index(op.f('ix_physical_locations_is_deleted'), table_name='physical_locations')
    op.drop_index(op.f('ix_physical_locations_id'), table_name='physical_locations')
    op.drop_table('physical_locations')
    op.drop_index(op.f('ix_ministries_is_deleted'), table_name='ministries')
    op.drop_index(op.f('ix_ministries_id'), table_name='ministries')
    op.drop_table('ministries')
    op.drop_index(op.f('ix_land_parcels_upi'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_is_deleted'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_id'), table_name='land_parcels')
    op.drop_table('land_parcels')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_councils_is_deleted'), table_name='councils')
    op.drop_index(op.f('ix_councils_id'), table_name='councils')
    op.drop_table('councils')
    op.drop_index(op.f('ix_commissions_is_deleted'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_centrales_is_deleted'), table_name='centrales')
    op.drop_index(op.f('ix_centrales_id'), table_name='centrales')
    op.drop_table('centrales')
    op.drop_index(op.f('ix_archive_ledger_books_is_deleted'), table_name='archive_ledger_books')
    op.drop_index(op.f('ix_archive_ledger_books_id'), table_name='archive_ledger_books')
    op.drop_table('archive_ledger_books')
    op.drop_index(op.f('ix_annual_parish_statistics_id'), table_name='annual_parish_statistics')
    op.drop_table('annual_parish_statistics')
    op.drop_index(op.f('ix_parishes_is_deleted'), table_name='parishes')
    op.drop_index(op.f('ix_parishes_id'), table_name='parishes')
    op.drop_index(op.f('ix_parishes_code'), table_name='parishes')
    op.drop_table('parishes')
    op.drop_index(op.f('ix_survey_responses_is_deleted'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_deaneries_is_deleted'), table_name='deaneries')
    op.drop_index(op.f('ix_deaneries_id'), table_name='deaneries')
    op.drop_table('deaneries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_parish_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deanery_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_surveys_is_deleted'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_land_use_categories_is_deleted'), table_name='land_use_categories')
    op.drop_index(op.f('ix_land_use_categories_id'), table_name='land_use_categories')
    op.drop_index(op.f('ix_land_use_categories_code'), table_name='land_use_categories')
    op.drop_table('land_use_categories')
    op.drop_index(op.f('ix_document_types_is_deleted'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_archdioceses_id'), table_name='archdioceses')
    op.drop_table('archdioceses')

    # PostgreSQL ENUM types are separate objects from the tables that reference
    # them, so dropping the tables does not drop the types. We remove them here
    # (after all referencing tables are gone) so that a clean `downgrade base`
    # leaves the database empty and a subsequent `upgrade head` can recreate the
    # full schema without "type already exists" errors.
    op.execute(
        "DROP TYPE IF EXISTS "
        "user_role_enum, appointment_role_enum, appointment_status_enum, "
        "canonical_status_enum, family_role_enum, gender_enum, "
        "clergy_type_enum, clergy_status_enum, commission_category_enum, "
        "council_type_enum, event_type_enum, donation_type_enum, "
        "mass_intention_type_enum, intention_type_enum, ministry_category_enum, "
        "land_use_enum, tenure_status_enum, payment_method_enum, "
        "sacrament_type_enum, sacrament_type_archive_enum, "
        "holy_orders_order_type_enum, religious_profession_type_enum, "
        "qr_code_purpose_enum"
    )
    # ### end Alembic commands ###
