import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { Input } from '../../components/common/Input';
import { domainApi } from '../../core/api/domain';
import { useActiveParish } from '../../core/hooks/useActiveParish';
import { useAuthStore } from '../../core/store/authStore';

type Row = Record<string, any>;
const bodyRoles = ['SUPER_ADMIN', 'CHANCELLOR', 'PARISH_PRIEST'];

export const GovernancePage: React.FC = () => {
  const client = useQueryClient();
  const { activeParishId } = useActiveParish();
  const role = useAuthStore((state) => state.user?.role || '');
  const canManageBodies = bodyRoles.includes(role);
  const canSchedule = ['PARISH_SECRETARY', 'MINISTRY_LEADER'].includes(role);
  const [body, setBody] = useState({ name: '', category: 'OTHER', council_type: 'PARISH_PASTORAL', leader_name: '', president_name: '' });
  const [meeting, setMeeting] = useState({ title: '', meeting_date: new Date().toISOString().slice(0, 10), venue: '', council_id: '', commission_id: '', agenda: '' });
  const [selectedMeeting, setSelectedMeeting] = useState<Row | null>(null);
  const [minute, setMinute] = useState({ title: '', content: '' });
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const queryKey = ['governance', activeParishId];
  const commissions = useQuery({ queryKey: [...queryKey, 'commissions'], queryFn: () => domainApi.listCommissions(activeParishId!), enabled: Boolean(activeParishId) });
  const councils = useQuery({ queryKey: [...queryKey, 'councils'], queryFn: () => domainApi.listCouncils(activeParishId!), enabled: Boolean(activeParishId) });
  const meetings = useQuery({ queryKey: [...queryKey, 'meetings'], queryFn: () => domainApi.listGovernanceMeetings(activeParishId!), enabled: Boolean(activeParishId) });
  const minutes = useQuery({ queryKey: ['meeting-minutes', selectedMeeting?.id], queryFn: () => domainApi.listMeetingMinutes(selectedMeeting!.id), enabled: Boolean(selectedMeeting?.id) });
  const refresh = () => client.invalidateQueries({ queryKey });
  const createCommission = useMutation({ mutationFn: () => domainApi.createCommission({ name: body.name, category: body.category, leader_name: body.leader_name || null, parish_id: activeParishId }), onSuccess: () => { setBody({ ...body, name: '', leader_name: '' }); setNotice('Commission created.'); setError(null); refresh(); }, onError: (e: any) => setError(e?.response?.data?.detail || 'Unable to create commission.') });
  const createCouncil = useMutation({ mutationFn: () => domainApi.createCouncil({ name: body.name, council_type: body.council_type, president_name: body.president_name || null, parish_id: activeParishId }), onSuccess: () => { setBody({ ...body, name: '', president_name: '' }); setNotice('Council created.'); setError(null); refresh(); }, onError: (e: any) => setError(e?.response?.data?.detail || 'Unable to create council.') });
  const createMeeting = useMutation({ mutationFn: () => domainApi.createGovernanceMeeting({ ...meeting, parish_id: activeParishId, council_id: meeting.council_id || null, commission_id: meeting.commission_id || null, venue: meeting.venue || null, agenda: meeting.agenda || null }), onSuccess: () => { setNotice('Meeting scheduled.'); setError(null); refresh(); }, onError: (e: any) => setError(e?.response?.data?.detail || 'Unable to schedule meeting.') });
  const addMinute = useMutation({ mutationFn: () => domainApi.addMeetingMinutes(selectedMeeting!.id, minute), onSuccess: () => { setMinute({ title: '', content: '' }); setNotice('Minutes saved.'); setError(null); client.invalidateQueries({ queryKey: ['meeting-minutes', selectedMeeting?.id] }); }, onError: (e: any) => setError(e?.response?.data?.detail || 'Unable to save minutes.') });
  const updateStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => domainApi.updateGovernanceMeeting(id, { status }), onSuccess: () => { setNotice('Meeting status updated.'); refresh(); } });

  return <div className="space-y-6">
    <header><h1 className="text-xl font-bold text-gray-900">Governance and meetings</h1><p className="mt-1 text-xs text-gray-500">Manage parish consultative bodies, meeting schedules, decisions, and official minutes.</p></header>
    {error && <p role="alert" className="rounded border border-red-200 bg-red-50 p-2 text-sm text-red-700">{error}</p>}{notice && <p role="status" className="rounded border border-green-200 bg-green-50 p-2 text-sm text-green-700">{notice}</p>}
    {canManageBodies && <div className="grid gap-4 lg:grid-cols-2">
      <Card title="Register commission"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); setError(null); createCommission.mutate(); }}><Input label="Name" required value={body.name} onChange={(e) => setBody({ ...body, name: e.target.value })} /><label className="block text-sm">Commission category<select className="mt-1 w-full rounded-lg border px-3 py-2" value={body.category} onChange={(e) => setBody({ ...body, category: e.target.value })}>{['FAMILY', 'EDUCATION', 'YOUTH', 'LITURGY', 'CARITAS_SOCIAL', 'VOCATIONS', 'COMMUNICATIONS', 'JUSTICE_PEACE', 'HEALTH', 'OTHER'].map((x) => <option key={x}>{x}</option>)}</select></label><Input label="Leader" value={body.leader_name} onChange={(e) => setBody({ ...body, leader_name: e.target.value })} /><Button size="sm" type="submit" disabled={!activeParishId || createCommission.isPending}>Save commission</Button></form></Card>
      <Card title="Register council"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); setError(null); createCouncil.mutate(); }}><Input label="Name" required value={body.name} onChange={(e) => setBody({ ...body, name: e.target.value })} /><label className="block text-sm">Council type<select className="mt-1 w-full rounded-lg border px-3 py-2" value={body.council_type} onChange={(e) => setBody({ ...body, council_type: e.target.value })}>{['PARISH_PASTORAL', 'PARISH_ECONOMIC', 'DIOCESAN_PASTORAL', 'PRESBYTERIUM', 'COLLEGE_OF_CONSULTERS', 'ECONOMIC_AFFAIRS'].map((x) => <option key={x}>{x}</option>)}</select></label><Input label="President" value={body.president_name} onChange={(e) => setBody({ ...body, president_name: e.target.value })} /><Button size="sm" type="submit" disabled={!activeParishId || createCouncil.isPending}>Save council</Button></form></Card>
    </div>}
    {canSchedule && <Card title="Schedule a meeting"><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3" onSubmit={(e) => { e.preventDefault(); setError(null); createMeeting.mutate(); }}><Input label="Meeting title" required value={meeting.title} onChange={(e) => setMeeting({ ...meeting, title: e.target.value })} /><Input label="Date" type="date" required value={meeting.meeting_date} onChange={(e) => setMeeting({ ...meeting, meeting_date: e.target.value })} /><Input label="Venue" value={meeting.venue} onChange={(e) => setMeeting({ ...meeting, venue: e.target.value })} /><label className="block text-sm">Council<select className="mt-1 w-full rounded-lg border px-3 py-2" value={meeting.council_id} onChange={(e) => setMeeting({ ...meeting, council_id: e.target.value, commission_id: '' })}><option value="">No council</option>{councils.data?.map((x: Row) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block text-sm">Commission<select className="mt-1 w-full rounded-lg border px-3 py-2" value={meeting.commission_id} onChange={(e) => setMeeting({ ...meeting, commission_id: e.target.value, council_id: '' })}><option value="">No commission</option>{commissions.data?.map((x: Row) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Input label="Agenda" value={meeting.agenda} onChange={(e) => setMeeting({ ...meeting, agenda: e.target.value })} /><div className="flex items-end"><Button size="sm" type="submit" disabled={!activeParishId || createMeeting.isPending}>Schedule</Button></div></form></Card>}
    <Card title="Parish councils and commissions"><div className="grid gap-4 md:grid-cols-2"><div><h2 className="mb-2 text-sm font-semibold">Councils</h2>{councils.data?.map((x: Row) => <p key={x.id} className="border-b py-2 text-sm">{x.name} <span className="text-xs text-gray-500">· {x.council_type}</span></p>)}</div><div><h2 className="mb-2 text-sm font-semibold">Commissions</h2>{commissions.data?.map((x: Row) => <p key={x.id} className="border-b py-2 text-sm">{x.name} <span className="text-xs text-gray-500">· {x.category}</span></p>)}</div></div></Card>
    <Card title="Meetings"><div className="space-y-2">{meetings.data?.map((item: Row) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3"><button className="text-left" onClick={() => { setSelectedMeeting(item); setError(null); }}><strong className="text-sm">{item.title}</strong><span className="ml-2 text-xs text-gray-500">{item.meeting_date} · {item.venue || 'No venue'} · {item.status}</span></button><div className="flex gap-2">{canSchedule && <Button size="sm" variant="outline" onClick={() => updateStatus.mutate({ id: item.id, status: item.status === 'SCHEDULED' ? 'HELD' : 'SCHEDULED' })}>{item.status === 'SCHEDULED' ? 'Mark held' : 'Reopen'}</Button>}<Button size="sm" variant="outline" onClick={() => setSelectedMeeting(item)}>Minutes</Button></div></div>)}</div></Card>
    {selectedMeeting && <Card title={`Minutes · ${selectedMeeting.title}`}>{canSchedule && <form className="mb-4 space-y-3" onSubmit={(e) => { e.preventDefault(); addMinute.mutate(); }}><Input label="Record title" required value={minute.title} onChange={(e) => setMinute({ ...minute, title: e.target.value })} /><label className="block text-sm">Minutes / decisions<textarea className="mt-1 min-h-28 w-full rounded-lg border border-gray-300 p-3" value={minute.content} onChange={(e) => setMinute({ ...minute, content: e.target.value })} /></label><Button size="sm" type="submit" disabled={addMinute.isPending}>Save official minutes</Button></form>}{minutes.data?.map((item: Row) => <div key={item.id} className="border-t py-3"><strong className="text-sm">{item.title}</strong><p className="whitespace-pre-wrap text-xs text-gray-600">{item.content}</p></div>)}</Card>}
  </div>;
};
