export const API_ENDPOINTS = {
  public: {
    overview: '/public/overview',
  },
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    users: '/auth/users',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  geography: {
    deaneries: '/geography/deaneries',
    parishes: '/geography/parishes',
    parishDetail: (parishId: string) => `/geography/parishes/${parishId}`,
    centrales: (parishId: string) => `/geography/parishes/${parishId}/centrales`,
    scc: (centraleId: string) => `/geography/centrales/${centraleId}/scc`,
  },
  faithful: {
    list: '/faithful',
    detail: (id: string) => `/faithful/${id}`,
    create: '/faithful',
    families: '/faithful/families',
    familyDetail: (id: string) => `/faithful/families/${id}`,
    familyMembers: (id: string) => `/faithful/families/${id}/members`,
  },
  sacraments: {
    baptism: '/sacraments/baptism',
    confirmation: '/sacraments/confirmation',
    matrimony: '/sacraments/matrimony',
    issueCertificate: '/sacraments/certificates/issue',
    verifyCertificate: (token: string) => `/sacraments/certificates/verify/${encodeURIComponent(token)}`,
    amendments: '/sacraments/amendments',
    recordDetail: (type: string, id: string) => `/sacraments/records/${encodeURIComponent(type)}/${id}`,
    reviewAmendment: (id: string) => `/sacraments/amendments/${id}/review`,
  },
  clergy: {
    list: '/clergy/priests',
    detail: (id: string) => `/clergy/priests/${id}`,
    create: '/clergy/priests',
    assignments: '/clergy/assignments',
    priestAssignments: (id: string) => `/clergy/priests/${id}/assignments`,
  },
  liturgy: {
    masses: '/liturgy/mass-schedules',
    intentions: '/liturgy/intentions',
    intentionDetail: (id: string) => `/liturgy/intentions/${id}`,
  },
  finance: {
    donations: '/finance/donations',
    donationDetail: (id: string) => `/finance/donations/${id}`,
    summary: '/finance/summary',
    reconciliation: '/finance/reconciliation',
  },
  ministries: {
    list: '/ministries/',
    create: '/ministries/',
  },
  landAssets: {
    parcels: '/land-assets/parcels',
    parcelDetail: (id: string) => `/land-assets/parcels/${id}`,
    buildings: '/land-assets/buildings',
    parcelBuildings: (parcelId: string) => `/land-assets/parcels/${parcelId}/buildings`,
    parcelLeases: (parcelId: string) => `/land-assets/parcels/${parcelId}/leases`,
    leases: '/land-assets/leases',
    leaseInstallments: (leaseId: string) => `/land-assets/leases/${leaseId}/installments`,
    leasePayment: (installmentId: string) => `/land-assets/leases/installments/${installmentId}/payment`,
    parcelTaxAssessments: (parcelId: string) => `/land-assets/parcels/${parcelId}/tax-assessments`,
    taxPayments: (taxRecordId: string) => `/land-assets/tax-assessments/${taxRecordId}/payments`,
  },
  governance: {
    commissions: '/governance/commissions',
    councils: '/governance/councils',
    meetings: '/governance/meetings',
    meetingMinutes: (id: string) => `/governance/meetings/${id}/minutes`,
  },
  surveys: {
    list: '/surveys',
    create: '/surveys',
    detail: (id: string) => `/surveys/${id}`,
    responses: (id: string) => `/surveys/${id}/responses`,
    summary: (id: string) => `/surveys/${id}/summary`,
  },
  archive: {
    books: '/archive/books',
    uploadPage: '/archive/pages',
    pages: (bookId: string) => `/archive/books/${bookId}/pages`,
    createPage: '/archive/pages',
    pageDetail: (pageId: string) => `/archive/pages/${pageId}`,
    triggerOcr: (pageId: string) => `/archive/pages/${pageId}/ocr`,
    reviewPage: (pageId: string) => `/archive/pages/${pageId}/review`,
    rescanPage: (pageId: string) => `/archive/pages/${pageId}/rescan`,
    downloadPage: (pageId: string) => `/archive/pages/${pageId}/file`,
    searchPages: '/archive/pages/search',
  },
  documents: {
    list: '/documents',
    upload: '/documents/upload',
    download: (id: string) => `/documents/${id}/download`,
    disposition: (id: string) => `/documents/${id}/disposition`,
  },
  statistics: {
    parishReports: '/statistics/parish-reports',
    reconcileParishReport: (parishId: string, year: number) => `/statistics/parish-reports/${parishId}/${year}/reconciliation`,
    submitReport: '/statistics/parish-report',
    annuarioPontificio: '/statistics/annuario-pontificio',
    indicators: '/statistics/indicators',
    computeIndicator: (key: string) => `/statistics/indicators/${key}`,
  },
};

